/**
 * Project Euler - Problem 2
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89.....
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 *
 * @author Bailey Belvis
 */
public class Problem2
{
	private final static int solution = 4613732;

	/**
	 * Main
	 *
	 * @param args
	 *        arg!
	 */
	public static void main(final String[] args)
	{
		// Solution 1
		solutionOne();
	}

	/**
	 * Loop from 0 to 4million and check every number.
	 */
	static void solutionOne()
	{
		int answer = 0;
		int previous = 1;
		int current = 1;
		int next = 1;

		while (current < 4000000) {
			if ((current % 2) == 0) {
				answer += current;
			}

			next = previous + current;
			previous = current;
			current = next;
		}

		print(answer);
	}

	/**
	 * Prints a value.
	 *
	 * @param value
	 *        int
	 */
	static void print(final int value)
	{
		if (value == solution) {
			System.out.println("Correct: " + value); //$NON-NLS-1$
		}
		else {
			System.out.println("Incorrect: " + value); //$NON-NLS-1$
		}

	}

}
